version: '2'
services:
  mongodb:
    image: mongo:latest
    ports:
        - 27017:27017
    volumes:
      - /data/db
      - ./data:/import
  redis:
    image: redis
    ports:
        - "6379"
  node:
    build: ./node/
    volumes:
      - .:/src
    ports:
      - 3000:3000
    command: /entrypoint.sh
