version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    links:
      - redis
    command: python app.py
    container_name: service_web
    volumes:
      - ./web:/usr/src/app
  redis:
    image: "redis:alpine"
    container_name: service_redis
  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
        - "5672:5672"
    expose:
        - "15672"
    environment:
        RABBITMQ_DEFAULT_USER: 'v6-rabbitmq'
        RABBITMQ_DEFAULT_PASS: 'v6-rabbitmq'
    container_name: 'service_rabbitmq'
  mongo:
    image: mongo:latest
    container_name: service_mongo
    ports:
        - 27017:27017
